### ISSUE TITLE
error when resizing height of the window

### ISSUE THREAD

**Issue by veksha** [veksha/cuda_mo_file_viewer#3]
repro: make height of the window very very small.
@Alexey-T, CudaText bug?

![image](https://user-images.githubusercontent.com/275333/229339018-64b0da10-99fc-480a-8f2e-29ea84291718.png)

**Comment by Alexey-T** [comment]
LCL bug. Pls set the "w_min" and "h_min" form properties.

**Comment by veksha** [comment]
OK.
