### ISSUE TITLE
Some escaping of spec chars is missing

### ISSUE THREAD

**Issue by CudaText-addons** [veksha/cuda_mo_file_viewer#7]
First apply my PR.
Next, when I look at this MO file
[cuda_mo_file_viewer.zip](https://github.com/veksha/cuda_mo_file_viewer/files/11180074/cuda_mo_file_viewer.zip)

I see that contents of listview does not match the contents of memo1/memo2.
for selected item.
![Screenshot from 2023-04-07 19-06-12](https://user-images.githubusercontent.com/17549064/230641398-0031de3b-be80-4206-b2c8-2aa990cf104b.png)

maybe because selected item contains CR-separated strings and plugin does not ESCAPE CR-chars.

**Comment by CudaText-addons** [comment]
My quick fix
```python
    def open_file(self):
        self.filename = dlg_file(True, '', '', '*.mo|*.mo', _('Please, provide path to .mo file'))
        if self.filename:
            dlg_proc(self.hdlg, DLG_PROP_SET, prop={'cap': CAPTION + ' - ' + self.filename})
            translation = gettext.GNUTranslations(open(self.filename, 'rb'))
            self.messages = [str(n)+'\r'+k.replace('\t',chr(3)).replace('\r','|')+'\r'+v.replace('\t',chr(3)).replace('\r','|')+'\t' for n, (k, v) in 
```

**Comment by veksha** [comment]
> maybe because selected item contains TAB-separated strings and plugin does not ESCAPE tab-chars.

plugin does escape "\t", but does not escape "\r".

**Comment by veksha** [comment]
would you do another PR? (quick fix)

**Comment by Alexey-T** [comment]
Posted PR

**Comment by veksha** [comment]
you can ask users if they want `\r` to be shown like `\\r`
(for me `|` is fine too)

![image](https://user-images.githubusercontent.com/275333/230645855-16d33bdf-907a-49d5-89db-0aaa9eaa5963.png)

thanks for fixes!
